path:
  input: ./input
  metaOutput: ./output/meta
#  metaOutput: src/test/java/meta
  jsonOutput: ./output/json
head:
  packageName: meta
  imps:
    - java.util.Map
    - java.util.LinkedHashMap
    - java.util.Collection
    - java.util.List
    - java.util.stream.Collectors
    - java.util.stream.Stream
    - org.mingxuan.util.JsonUtil
excel:
  snName: sn
  # 竖表
  vertical:
    - Vtest
json:
  pretty: true